Fix use of incorrect method
When checking `CNAME` records, the code calls:
```
self.resolver.query(cname_host, "A", total_rechecks)
```

Which results in an integer argument being given for the `name_server` argument in the `resolver.query` method which has the signature:
```
def query(self, hostname, query_type = 'ANY', name_server = False, use_tcp = False):
```
And causes an error to be raised in `dnslib`:
```
 File "dnslib/dns.py", line 375, in send
    sock.sendto(self.pack(),(dest,port))
TypeError: coercing to Unicode: need string or buffer, int found
```

It seems from the call signature intended to be recursive call to the `check` method itself with a preservation of the retry count so that's what I put in.